/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cuestionario;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JRadioButton;

/**
 *
 * @author pc
 */
public class FormularioCuestionario extends javax.swing.JFrame {
//vamos a generar un List de radio buttons

    List<JRadioButton> radios = new ArrayList<>();
    List<Pregunta> preguntas = new ArrayList<>();
    int preguntaActual=0;


    public FormularioCuestionario() {
        initComponents();
        //aqui dentro del constructor de nuestro formularion
        //invocamos nuestro metodo generarCuestionario()
        //llenamos los radios
        radios.add(radioTituloOpcion0);
        radios.add(radioTituloOpcion1);
        radios.add(radioTituloOpcion2);
        radios.add(radioTituloOpcion3);

        generarCuestionario();
    }

    //aqui vamos a pegar el metodo
    public void generarCuestionario() {
        //con el modelo contruido podemos representar nuestra pregunta y mostrarla
        //primero creamos las opciones
          Opcion op1 = new Opcion();
        op1.setTitulo("Londres");
        op1.setCorrecta(false);

        Opcion op2 = new Opcion();
        op2.setTitulo("Roma");
        op2.setCorrecta(false);

        Opcion op3 = new Opcion();
        op3.setTitulo("Paris");
        op3.setCorrecta(true);

        Opcion op4 = new Opcion();
        op4.setTitulo("Orlando");
        op4.setCorrecta(false);

        //Sigue el arreglo de opcion
        Opcion[] opciones = {op1, op2, op3, op4};
        Pregunta p1 = new Pregunta();
        p1.setTitulo("¿Cual es la capital de Francia");
        p1.setOpciones(opciones);
        
        //Opiciones de la pregumta Numero 2
        Opcion op21 = new Opcion();
        op21.setTitulo("Atlantico");
        op21.setCorrecta(false);

        Opcion op22 = new Opcion();
        op22.setTitulo("Indico");
        op22.setCorrecta(false);

        Opcion op23 = new Opcion();
        op23.setTitulo("Artico");
        op23.setCorrecta(false);

        Opcion op24 = new Opcion();
        op24.setTitulo("Pacifico");
        op24.setCorrecta(true);

        //Sigue el arreglo de opcion
        Opcion[] opciones2 = {op21, op22, op23, op24};
        Pregunta p2 = new Pregunta();
        p2.setTitulo("¿Cual es el oceano más grande del mundo?");
        p2.setOpciones(opciones2);


        //Vamos a adaptar el cuestioanario a lo que ya teniamos
        Cuestionario c = new Cuestionario();
        //Creamos el list de preguntas

        //Se agrega a este list la unica prgunta que tenemos
        preguntas.add(p1);
        preguntas.add(p2);
        //A este list le vamos a proporcionar el valor del correspondiente
        //cuestioanrio
        c.setPreguntas(preguntas);
//Primero ajustamos el titulo de la primer pregunta en la etiqueta de la preunta
    mostrarPregunta(preguntaActual);
        
    }
public void mostrarPregunta(int indicePregunta){
    //Checar si el indice de pregunta no rebaso el numero de preguntas
    //dentro del arraylist preguntas.
    etiquetaTituloPregunta.setText(preguntas.get(indicePregunta).getTitulo());

        //Llenamos con el modelo los radio buttons
        for (int i = 0; i < radios.size(); i++) {
            radios.get(i).setText(preguntas.get(indicePregunta).getOpciones()[i].getTitulo());
        }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        etiquetaTituloPregunta = new javax.swing.JLabel();
        radioTituloOpcion0 = new javax.swing.JRadioButton();
        radioTituloOpcion1 = new javax.swing.JRadioButton();
        radioTituloOpcion2 = new javax.swing.JRadioButton();
        radioTituloOpcion3 = new javax.swing.JRadioButton();
        etiqueta = new javax.swing.JLabel();
        botonRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTituloPregunta.setText("jLabel1");

        grupo.add(radioTituloOpcion0);
        radioTituloOpcion0.setText("jRadioButton1");

        grupo.add(radioTituloOpcion1);
        radioTituloOpcion1.setText("jRadioButton2");

        grupo.add(radioTituloOpcion2);
        radioTituloOpcion2.setText("jRadioButton3");

        grupo.add(radioTituloOpcion3);
        radioTituloOpcion3.setText("jRadioButton4");

        botonRespuesta.setText("verificar");
        botonRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(botonRespuesta)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioTituloOpcion0)
                            .addComponent(etiquetaTituloPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioTituloOpcion1))
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioTituloOpcion3)
                            .addComponent(radioTituloOpcion2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(etiquetaTituloPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(radioTituloOpcion0)
                .addGap(18, 18, 18)
                .addComponent(radioTituloOpcion1)
                .addGap(18, 18, 18)
                .addComponent(radioTituloOpcion2)
                .addGap(18, 18, 18)
                .addComponent(radioTituloOpcion3)
                .addGap(31, 31, 31)
                .addComponent(botonRespuesta)
                .addGap(18, 18, 18)
                .addComponent(etiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRespuestaActionPerformed

        // TODO add your handling code here:
        //aqui se invocar el algoritmo 
        //vamos a ver si funciona el isSelected()
        //para ello probamos con el primero radiotitulo0
        //boolean r0=radioTituloOpcion0.isSelected();
        //ahora ese booleano lo imprimimos en la etiqueta respuesta
        // etiqueta.setText("Tu respuesta es: "+r0);
        //vamos primero a iterar el arreglo de radios
        //primero obtenemos la primer pregunta de nuestro listado de preguntas
        if(preguntaActual<preguntas.size()){
        Opcion[] opciones = preguntas.get(preguntaActual).getOpciones();
       boolean acierto=false;
        for (int i = 0; i < radios.size(); i++) {
            if (radios.get(i).isSelected() && opciones[i].isCorrecta()) {   
                acierto=true;
                break;
            }
        } //Aqui termina el for
       etiqueta.setText("Tu respuesta es  "+acierto);
       //Este incremento hace que la siguiente pregunta sea incrementada en 1
          preguntaActual++;
            System.out.println("La pregunta actual es"+preguntaActual);
            System.out.println("Las preguntas totales son "+preguntas.size());
        //Para  que no se lance la expcion hacer que el metodo mostrar pregunta
        //no muestre la preguta si el tamaño de ArrayList ue se llama preguntas
        // ya no tiene mas preguntas, debes de apoyarte del metodo size()
      mostrarPregunta(preguntaActual);
      
      
          }
        
     

    }//GEN-LAST:event_botonRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
   try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
           
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioCuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRespuesta;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel etiquetaTituloPregunta;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JRadioButton radioTituloOpcion0;
    private javax.swing.JRadioButton radioTituloOpcion1;
    private javax.swing.JRadioButton radioTituloOpcion2;
    private javax.swing.JRadioButton radioTituloOpcion3;
    // End of variables declaration//GEN-END:variables
  public boolean checarRespuesta(Opcion[] opciones) {
        boolean correcta = false;

        for (int i = 0; i < radios.size(); i++) {
            if (radios.get(i).isSelected() && opciones[i].isCorrecta()) {
                System.out.println("Ya le atinaste");
                correcta = true;
                break;
            }
        }

        return correcta;
  }


}
